apiVersion: v1
kind: ReplicationController
metadata:
  name: devopscicdapps
spec:
  replicas: 2
  selector:
    app: devopscicdapps
  template:
    metadata:
      name: devopscicdapps
      labels:
        app: devopscicdapps
    spec:
      containers:
        - name: devopscicdapps
          image: imonbayazid/devopscicdapps:1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devopscicdapps
spec:
  selector:
    app: devopscicdapps
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
